//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jovo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Jovo : global::System.Configuration.ApplicationSettingsBase {
        
        private static Jovo defaultInstance = ((Jovo)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Jovo())));
        
        public static Jovo Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string System_Tray_Icon_Middle_Click_Module_Name {
            get {
                return ((string)(this["System_Tray_Icon_Middle_Click_Module_Name"]));
            }
            set {
                this["System_Tray_Icon_Middle_Click_Module_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string System_Tray_Icon_Left_Click_Module_Name {
            get {
                return ((string)(this["System_Tray_Icon_Left_Click_Module_Name"]));
            }
            set {
                this["System_Tray_Icon_Left_Click_Module_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Module_Update_Remote_Path {
            get {
                return ((string)(this["Module_Update_Remote_Path"]));
            }
            set {
                this["Module_Update_Remote_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Jovo_Update_Remote_Path {
            get {
                return ((string)(this["Jovo_Update_Remote_Path"]));
            }
            set {
                this["Jovo_Update_Remote_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Jovo_Updater_Local_Path {
            get {
                return ((string)(this["Jovo_Updater_Local_Path"]));
            }
            set {
                this["Jovo_Updater_Local_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Jovo_Automatic_Updates {
            get {
                return ((bool)(this["Jovo_Automatic_Updates"]));
            }
            set {
                this["Jovo_Automatic_Updates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Module_Name_to_Run_When_PC_Locks {
            get {
                return ((string)(this["Module_Name_to_Run_When_PC_Locks"]));
            }
            set {
                this["Module_Name_to_Run_When_PC_Locks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Module_Name_to_Run_When_PC_Unlocks {
            get {
                return ((string)(this["Module_Name_to_Run_When_PC_Unlocks"]));
            }
            set {
                this["Module_Name_to_Run_When_PC_Unlocks"] = value;
            }
        }
    }
}
