//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jovo {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Jovo : global::System.Configuration.ApplicationSettingsBase {
        
        private static Jovo defaultInstance = ((Jovo)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Jovo())));
        
        public static Jovo Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NOTIFYEVENT_LEFT {
            get {
                return ((string)(this["NOTIFYEVENT_LEFT"]));
            }
            set {
                this["NOTIFYEVENT_LEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NOTIFYEVENT_MIDDLE {
            get {
                return ((string)(this["NOTIFYEVENT_MIDDLE"]));
            }
            set {
                this["NOTIFYEVENT_MIDDLE"] = value;
            }
        }
    }
}
